# CASE-1:

 **The data only with yearexperience and salary**

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df=pd.read_csv('/content/case_1.csv')
df

    YearsExperience   Salary
0               1.1  39343.0
1               1.3  46205.0
2               1.5  37731.0
3               2.0  43525.0
4               2.2  39891.0
5               2.9  56642.0
6               3.0  60150.0
7               3.2  54445.0
8               3.2  64445.0
9               3.7  57189.0
10              3.9  63218.0
11              4.0  55794.0
12              4.0  56957.0
13              4.1  57081.0
14              4.5  61111.0

In [11]:
X=df[['YearsExperience']] # independent

y=df['Salary'] #dependent

In [12]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X,y)

LinearRegression()

In [14]:
ans_of_model=reg.predict(X)

In [15]:
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y,ans_of_model)

4784.750838401652

In [17]:
from sklearn.metrics import r2_score

print(f'The Accuracy {r2_score(y,ans_of_model)}') #r2_score

The Accuracy 0.7020755183418668

In [24]:
X.shape[1]

1

In [25]:
#adjust_r2_score


value = 1 - ((1-r2_score(y,ans_of_model)) * (len(df)-1)) / ((len(df)-(X.shape[1])-1))

print(f'The Accuracy {value}')

The Accuracy 0.6791582505220104

# CASE - 2

**The data with yearsexperience and salary with one add coloumn of height**

checking wheather the column add is usefull or not

In [27]:
import numpy as np
import pandas as pd
import sklearn

In [28]:
df=pd.read_csv('/content/case_2.csv')
df.head()

   YearsExperience   Salary  Height
0              1.1  39343.0    1.47
1              1.3  46205.0    1.50
2              1.5  37731.0    1.52
3              2.0  43525.0    1.55
4              2.2  39891.0    1.57

In [29]:
X=df[['YearsExperience','Height']] # independent

y=df['Salary'] #dependent

In [30]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X,y)

LinearRegression()

In [31]:
ans_of_model=reg.predict(X)

In [32]:
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y,ans_of_model)

4479.644461989443

In [33]:
from sklearn.metrics import r2_score

print(f'The Accuracy {r2_score(y,ans_of_model)}') #r2_score

The Accuracy 0.7388592596500807

In [34]:
X.shape[1]

2

In [35]:
#adjust_r2_score


value = 1 - ((1-r2_score(y,ans_of_model)) * (len(df)-1)) / ((len(df)-(X.shape[1])-1))

print(f'The Accuracy {value}')

The Accuracy 0.6953358029250942


# checking wheather the column add is usefull or not

**This checked using the r2_score and adj_r2_score**

1. r2-score increases the accuracy -> when every a new column is added r2_score it's keep on increase the accuracy value doen't matter wheather the new column is a column important or not

2. But adjust_r2_score -> will increaser means it is import otherwise it is not important